## Write a Numpy program to compute the multiplication of two given matrixes

In [7]:
import numpy as np
matA = np.array([[5, 5], [7, 2]])
matB = np.array([[9, 2], [8, 6]])
print("Mat A:")
print(matA)
print("Mat B:")
print(matB)
result = np.dot(matA, matB)
print("Result")
print(result)

Mat A:
[[5 5]
 [7 2]]
Mat B:
[[9 2]
 [8 6]]
Result
[[85 40]
 [79 26]]


## Write a NumPy program to compute the determinant of a given square array

In [8]:
matA = np.array([[5, 5], [7, 2]])

In [11]:
deter = np.linalg.det(matA)
deter

-25.000000000000007

## Write a NumPy program to compute the cross product of two given vectors

In [ ]:
matA = np.array([[5, 5], [7, 2]])
matB = np.array([[9, 2], [8, 6]])
print("Mat A:")
print(matA)
print("Mat B:")
print(matB)

In [12]:
cross = np.cross(matA, matB)
cross

array([-35,  26])

## Write a NumPy program to compute the condition number of a given matrix
the condition number of a function measures how much the output value of the function can change for a small change in the input argument. This is used to measure how sensitive a function is to changes or errors in the input, and how much error in the output results from an error in the input.

*hint: look for something similar in the `linalg` module*

In [14]:
condition = np.linalg.cond(matA)

In [15]:
condition

3.860999722376436

## Write a NumPy program to compute the inverse of a given matrix

In [13]:
inverse = np.linalg.inv(matA)
inverse

array([[-0.08,  0.2 ],
       [ 0.28, -0.2 ]])